[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  REACT_APP_BACKEND_URL = "https://oncohealth.onrender.com"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
